import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";

import "./globals.css";

import { Footer, Header } from "@/components/shared";

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({ weight: ["100", "400", "700"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Future Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='es'>
      <body className='m-auto w-11/12'>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
